---
- include:              '../tasks/dependencies.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/install_python_packages.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_files.yml'
